name: pedidos_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.3
  google_maps_flutter_android: ^2.14.11
  google_maps_flutter_ios: ^2.13.2
  google_maps_flutter_web: ^0.5.10
  http: ^1.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
